<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Informazioni';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
       ATIPICA, COOPERATIVA SOCIALE ONLUS, È ATTIVA DAL 1997 NELL’AMBITO DELLE TOSSICO DIPENDENZE, NEL CONTRASTO AL DISAGIO DEI MINORI E PER LA TUTELA DEI PIÙ PICCOLI.
HA SEDI OPERATIVE A SIRTORI (LC) CON UNA COMUNITÀ PER TOSSICODIPENDENTI, A GIUSSANO (MB) DOVE HA REALIZZATO UN MODERNISSIMO CENTRO DIURNO PER ACCOGLIERE MINORI DEL TERRITORIO E A MILANO DOVE SVOLGE ATTIVITÀ
IN FAVORE DI FAMIGLIE E DI MINORI GRAZIE AL LAVORO DEI PROPRI PSICOLOGI ED EDUCATORI.</p>
<p>
ATIPICA COLLABORA CON NUMEROSE REALTÀ PUBBLICHE E PRIVATE, SOPRATTUTTO NELLA PROVINCIA DI MONZA E BRIANZA, MA ANCHE NEL TERRITORIO LECCHESE.
IN PARTICOLARE SI OCCUPA DI TUTELA DEI MINORI NELLE AREE DI SEREGNO (MB) E DI VIMERCATE (MB)
    </p>

</div>
